name: Android

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 50

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Start Appium Server
        run: |
          node -v
          npm install -g appium@v1.22.3
          appium -v
          appium --address 127.0.0.1 --port 4723 &

      - name: Create Android Emulator
        run: |
          $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-27;google_apis;x86"
          $ANDROID_HOME/tools/bin/avdmanager create avd --force -n TestEmulator -d pixel --package 'system-images;android-27;google_apis;x86'
          echo $ANDROID_HOME/emulator/emulator -list-avds
          echo "Starting emulator"
          nohup $ANDROID_HOME/emulator/emulator -avd TestEmulator -skin 1080x1920 -memory 1024 -engine qemu2 -netfast -no-audio -no-snapshot -accel on > /dev/null 2>&1 &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
          $ANDROID_HOME/platform-tools/adb devices
          echo "Emulator started"

      - name: Install Dependencies and Run Appium tests
        run: |
          mvn install

      - name: Upload Test Artifact - GitHub Action
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: target/surefire-reports