name: Android

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 50

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Start Appium Server
        run: |
          node -v
          npm install -g appium@v1.22.3
          appium -v
          appium --address 127.0.0.1 --port 4723 &

      - name: Create Emulator and Run Appium tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: mvn test

      - name: Upload Test Artifact - GitHub Action
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: target/surefire-reports