name: Android

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 50

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Start Appium Server
        run: |
          node -v
          npm install -g appium@v1.21.0
          appium -v

      - name: Create Android Emulator
        run: |
          export PATH=$PATH:$ANDROID_HOME/platform-tools
          export PATH=$PATH:$ANDROID_HOME/platform-tools/adb
          $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-29;google_apis;x86"
          $ANDROID_HOME/tools/bin/avdmanager create avd --force -n TestEmulator -d pixel --package 'system-images;android-29;google_apis;x86'
          $ANDROID_HOME/emulator/emulator -list-avds
          $ANDROID_HOME/emulator/emulator @TestEmulator &

      - name: Run Appium tests
        run: |
          $ANDROID_HOME/emulator/emulator -list-avds
          $ANDROID_HOME/emulator/emulator @TestEmulator &
          appium -a 127.0.0.1 -p 4723 &> appium_server.log &
          mvn install

      - name: Upload Test Artifact - GitHub Action
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: target/surefire-reports